# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviesBRQ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoviesBRQ
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'AlamofireObjectMapper'

  target 'MoviesBRQTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoviesBRQUITests' do
    # Pods for testing
  end

end
